### PR TITLE
Make the title clickable

### LINKED ISSUE #92: Make the title clickable
When you click on the title of the website, it redirects to the homepage. So whichever segment you are in of the website, you can easily return to home page with one click.

### PR DESCRIPTION
**Pull request by S-ishita**
Closes #92 
When you click on the title of the website, it redirects to the homepage. So whichever segment you are in of the website, you can easily return to home page with one click.

### CODE REVIEW

**Review by mrbhatt2348 — APPROVED** [review]

**Comment by S-ishita** [comment]
hey @mrbhatt2348 why this wasn not merged??

**Review by mrbhatt2348 — APPROVED** [review]

**Comment by mrbhatt2348** [comment]
> hey @mrbhatt2348 why this wasn not merged??
> 

@S-ishita the commit is having merge conflicts...

**Comment by S-ishita** [comment]
Resolved the conflicts @mrbhatt2348

**Comment by mrbhatt2348** [comment]
> Resolved the conflicts @mrbhatt2348 

@S-ishita done

**Comment by mrbhatt2348** [comment]
> Resolved the conflicts @mrbhatt2348 

@S-ishita done

**Pull request merged**
