### PR TITLE
Update readme file

### PR DESCRIPTION
**Pull request by Suryansh1720001**
Hello @mrbhatt2348 
This PR under the Issue of  #70 

## Features I added- 
- the contribution guidelines.
- the maintainer details
- new features for more attractiveness
- screenshot

Kindly review this PR and merge it accordingly with IWOC label. And after seeing the work can you put the hard label with it.

### CODE REVIEW

**Review by mrbhatt2348 — APPROVED** [review]

**Comment by Suryansh1720001** [comment]
Hello @mrbhatt2348 
Kindly add the IWOC with medium label.
This is not good thing, you just merge my code without adding the labels.

**Comment by mrbhatt2348** [comment]
> Hello @mrbhatt2348 
> Kindly add the IWOC with medium label.
> This is not good thing, you just merge my code without adding the labels.  
> 
> Reference #70 
> 
> image
> 

That is my part you don't need to worry about it and updating 3 parts of documentation doesn't give medium label of JWOC, so kindly take this into consideration before commenting on the pr

**Comment by Suryansh1720001** [comment]
okay @mrbhatt2348 
then add the easy label at least. You don't even add the IWOC label. So, what I should understand from this?

**Comment by mrbhatt2348** [comment]
> okay @mrbhatt2348 
> then add the easy label at least. You don't even add the IWOC label. So, what I should understand from this?

You should understand that maintainer is busy, just wait till 1 day, if still it is not done, then you should comment

**Comment by Suryansh1720001** [comment]
@mrbhatt2348 
Now 24+ hours are completed. Can you add the label now?

**Comment by Suryansh1720001** [comment]
@mrbhatt2348 
I think you have a lot of important work to do. 
You easily combined my PR and reviewed the code because you knew how much new information I added to the documentation. 
However, I don't think it would be easy for you to add the labels here or in the issue section. It is very difficult for you. 
Thank you for let me know this side of open-source also.

**Pull request merged**
