### PR TITLE
Added some css property

### PR DESCRIPTION
**Pull request by Aniket-011**
Its my initial modification on this web page.

### CODE REVIEW

**Review by Aniket-011 — COMMENTED** [review]
I thiink this is enough for this web page

**Comment by Aniket-011** [comment]
Adding some property

**Review by mrbhatt2348 — APPROVED** [review]

**Comment by mrbhatt2348** [comment]
@Aniket-011 
Bro, I am really sorry as I cannot merge your pr under JWOC as it was requested 4 days ago, and coding period of JWOC began today only

**Comment by Aniket-011** [comment]
I request you to please assign me this issue again.
Hope  you understand

**Pull request closed without merging**
