### PR TITLE
website link added in readme file 

### PR DESCRIPTION
**Pull request by Ritu-2001**

### CODE REVIEW

**Comment by Ritu-2001** [comment]
@mrbhatt2348  i also make some changes in index.html and style.css file because i add footer section ...........
please tell me changes are done or not ??

**Comment by mrbhatt2348** [comment]
@Ritu-2001 kindly add a video demonstrating the changes you made

**Comment by Ritu-2001** [comment]
Ok

**Comment by Ritu-2001** [comment]
Screenshot (161)

**Comment by Ritu-2001** [comment]
i make this footer ,,, that's why changes other file ,,,,,,,, 
But as per my issue i want to add website link to readme file , If you say I will only change the read me file  please give me response

**Review by Ritu-2001 — COMMENTED** [review]
only  README file is present all other unnecessary files are deleted

**Comment by Ritu-2001** [comment]
add website link in readme file please check it

**Review by mrbhatt2348 — APPROVED** [review]

**Pull request merged**
