### PR TITLE
made signup.html similar to login.html

### PR DESCRIPTION
**Pull request by deepbeatz**
Screenshot 2023-02-17 19 53 41

### CODE REVIEW

**Comment by mrbhatt2348** [comment]
@deepbeatz ✅

**Review by mrbhatt2348 — APPROVED** [review]

**Comment by mrbhatt2348** [comment]
@deepbeatz I have merged the request but check about that three icons appearing in your image near password section

**Comment by deepbeatz** [comment]
@mrbhatt2348 sir that is just my chrome extension.

**Comment by deepbeatz** [comment]
avira password manager

**Comment by mrbhatt2348** [comment]
> avira password manager

Okay 👍

**Pull request merged**
